#!/bin/bash
src_doc="tmp-doc"
doc="doc"
while [ $# -gt 0 ]; do
    case $1 in
        -x) set -x;shift;;
        -f) doc="tmp-doc";;
    esac
    shift
done

nom=spams
/bin/rm -f $nom.o ${nom}_wrap.o ${nom}_wrap.py $nom.pyc ${nom}_wrap.cpp ${nom}_wrap-windows.cpp _${nom}_wrap.so *.pyc
/bin/rm -rf build dist $src_doc $doc spams.new.py spams-*.tar.gz spams-*.exe setup.py
/bin/rm -f MANIFEST Release-name
/bin/rm -f INSTALL-package INSTALL-windows README
/bin/rm -f dict.png dict1.png dict2.png
/bin/rm -rf python2-install python3-install
/bin/rm -rf __pycache__
