#!/bin/sh
case $1 in -x) set -x;shift;;esac

usage() {
    echo "Usage: $0 [-tar]"
    echo " prepare a spams-python/ for distribution in ./dist/"
    echo "  -tar : make a tar file"
    exit 1
}

mktar=0
case $1 in
    -tar) mktar=1;shift;;
esac
[ $# -gt 0 ] && usage

nom=spams
/bin/rm -rf dist
swig -c++ -python -o ${nom}_wrap.cpp $nom.i
python setup.py sdist
cdir=`/bin/pwd`
cd dist
tar zxf *.tar.gz
/bin/rm -f *.tar.gz
dir=`/bin/ls | head -1`
tmpd=dist/$dir
cd $cdir
cp -p spams.h $tmpd
./docmatlab2python $tmpd/spams
mv $tmpd/spams.new.py $tmpd/spams.py
cp -p ../extdata/* $tmpd
cp -p INSTALL-package ../../doc/doc_spams.pdf $tmpd
rm -f $tmpd/README

cd dist
name=spams-python
mv $dir $name
[ $mktar -eq 0 ] && exit 0
tgz=$name-`date +%Y-%m-%d`.tar.gz
tar zcf $tgz $name
cp -p $tgz ../$name.tar.gz
exit 0
