#!/bin/bash
case $1 in -x) set -x;shift;;esac
# The main version number is in ../Version

die () {
    echo $*
    exit 1
}

usage() {
    echo "Usage: $0 [-f]"
    echo " prepare a spams-python/ for distribution in ./dist/"
    echo "  -f : do not rebuild the doc from scratch"
    echo "  -py3 : for python3 compatibility (to do in swig/python3 directory)"
    exit 1
}

rmdoc=1
PYTHON=$(which python2)
while [ $# -gt 0 ]; do
    case $1 in
        -f) rmdoc=0;shift;;
        -py3) PYTHON=$(which python3); if [ -z $PYTHON ]; then PYTHON=$(which python); fi;;
    esac
    shift
done
[ $# -gt 0 ] && usage

WDIR=$(pwd)
CP=/bin/cp
MV=/bin/mv
RM=/bin/rm

[ -x ./mkdist ] || die "You must be in the directory containing mkdist"
[ -x ../mkRelease ] || die "No prog ../mkRelease"
[ -x ../setRelease ] || die "No prog ../setRelease"
fullvers=`../mkRelease -f`
../setRelease setup.py.in > setup.py

../setRelease README.md > README
../setRelease INSTALL-package.in > INSTALL-package
../setRelease INSTALL-windows.in > INSTALL-windows

PY_OPT=""
# if [[ $PYTHON =~ "python3" ]];
# then
#     PY_OPT="-py3"
# fi

name=spams
/bin/rm -rf dist

## create of copy of ../spams.h
$MV ${name}.h ${name}.h.bak
$CP $(readlink ${name}.h.bak) .

## create ./dist and copy before creating the interface with swig


SWIG=swig
$SWIG -c++ $PY_OPT -python -DWINDOWS -o ${name}_wrap-windows.cpp ${name}.i
patch -i ${name}_wrap-windows.cpp.patch ${name}_wrap-windows.cpp
$SWIG -c++ $PY_OPT -python -o ${name}_wrap.cpp ${name}.i
patch -i ${name}_wrap.cpp.patch ${name}_wrap.cpp
$PYTHON setup.py sdist
[ $? -eq 0 ] || die "setup error; cannot continue"

$RM ${name}.h
$MV ${name}.h.bak ${name}.h

cdir=`/bin/pwd`
cd dist
tar zxf *.tar.gz
/bin/rm -f *.tar.gz
# dir=`/bin/ls | head -1`
# tmpd=dist/$dir
# cd $cdir
# cp -p spams.h $tmpd
# ./docmatlab2python $tmpd/spams
# mv $tmpd/spams.new.py $tmpd/spams.py
# rm -f $tmpd/boat.png $tmpd/lena.png
# mkdir $tmpd/extdata
# pwd
# cp -p ../extdata/boat.png ../extdata/lena.png $tmpd/extdata
# cp -p spams_wrap-windows.cpp $tmpd
# ../setRelease INSTALL-package.in >$tmpd/INSTALL-package
# ../setRelease INSTALL-windows.in >$tmpd/INSTALL-windows
# ../setRelease README.md >$tmpd/README.md
# ../setRelease README_dev.md >$tmpd/README_dev.md
#
# cp -p win-build.sh $tmpd
# # rm -f $tmpd/README
# # doc
# cd $cdir
# [ $rmdoc -ne 0 ] && /bin/rm -rf tmp-doc
# ../mkdoc
# doc=tmp-doc
# mkdir $tmpd/sphinx
# cp -a $doc/build/html/* $tmpd/sphinx
# cp -a $doc/html $tmpd
# cp -p $doc/doc_spams.pdf $tmpd
# cp -p $doc/build/latex/SPAMS.pdf $tmpd/python-interface.pdf
#
# echo "$fullvers" >$tmpd/Release-name
# cd dist
# name=spams-python
# if [[ $PYTHON =~ "python3" ]];
# then
#     name=spams-python3
# fi
# mv $dir $name
# tgz=$name-$fullvers.tar.gz
# tar zcf $tgz $name
# mv $tgz ../../../
# #cp -p $tgz ../${name}_svn.tar.gz
# exit 0
# # zip :
# zname=$name-$fullvers.zip
# find $name | zip -@ $zname
exit 0
