#!/bin/sh
case $1 in -x) set -x;shift;;esac

die () {
    echo "$1"
    exit 1
}

[ -x ./mkdoc ] || die "You must be in the directory containing this script"
export PYTHONPATH=""

doc=tmp-doc
cdir=`/bin/pwd`
/bin/rm -rf $doc
mkdir -p $doc/source/_static $doc/source/_templates $doc/build
[ -d $doc/source ] || die "Cannot create doc directory"

cd doc-src
cp Makefile make.bat $cdir/$doc
cp conf.py $cdir/$doc/source
cd $cdir
./mkpy spams
./docmatlab2python -sphinx $doc spams
cp spams_wrap.py _spams_wrap.so $doc

cd $doc
make html
make latex
cd build/latex
make all-pdf
cd $cdir
exit 0
