#!/bin/bash

##  clean files generated by ./mybuild

# help files
find man -name "*.Rd" | xargs rm

# src files
rm -r pkg/spams*

# swg generated files
rm spams.R
rm spams.cpp

# tar ball
VERSION=`cat ../Version`
if [ -f spams_$VERSION.tar.gz ];
then
    rm spams_$VERSION.tar.gz
fi
