#!/bin/sh
case $1 in -x) set -x;shift;;esac

die () {
    echo $*
    exit 1
}
ext=src;force=0
case $1 in -f) force=1;shift;;esac
name=spams-R
[ $# -eq 1 ] || die "Usage: $0 [-f] work-dir"

wdir=$1
dir=$wdir/$name
[ -d $wdir ] || die "No dir $wdir"
[ -x ./mkdist ] || die "Il faut etre dans le directoty original"
cur_dir=`/bin/pwd`
[ $force -gt 0 ] && /bin/rm -rf $dir
[ -d $dir ] && die "$dir existe deja"
mkdir $dir
[ -d $dir ] || die "cannot create $dir"
rdir=$dir
./docmatlab2R r_spams
./mybuild -nb
cp INSTALL $rdir
pngpkg=png_0.1-4.tar.gz
if [ -r $pngpkg ]; then
    cp -p $pngpkg $rdir
fi
cd pkg
tar chf - spams | (cd $rdir;tar xf -)
cd $wdir
tar zcf $name-`date +%Y-%m-%d`.tgz $name
exit 0

