source('spams.R')
dyn.load(paste("spams_wrap", .Platform$dynlib.ext, sep=""))
cacheMetaData(1)
x = rnorm(2000000,0,1)
tic = proc.time()
y1 = sort(x)
tac = proc.time()
print(tac - tic)
tic = proc.time()
y2 = spams.sort(x,TRUE)
tac = proc.time()
print (tac-tic)
print(min(abs(y2 - y1)))
